### ISSUE TITLE
Changing default value in azure

### ISSUE THREAD

**Issue by Krashto** [pglombardo/PasswordPusher#1022]
## Checklist

- [ X] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [ X] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How do you change default value in an azure container? I've looked through the azure setup (https://github.com/pglombardo/PasswordPusher/issues/277)
Everything works, but the part on the configuration changing language doesn't seem to work for me.
I've tried restarting the container, haven't had any success.

## 📎 Additional context

![image](https://user-images.githubusercontent.com/67296022/232044437-e89098f3-368b-4345-8c9b-991c65231b21.png)

**Comment by pglombardo** [comment]
This one is tricky and easy to miss:  there needs to be two underscores between `PWP` and `DEFAULT_LOCALE`.  So to set default locale, the environment variable should be `PWP__DEFAULT_LOCALE`.

If it helps, copy/paste the variable direction from [Configuration.md](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md) helps.

Let me know if this fixes is for you.

**Comment by pglombardo** [comment]
Hi @Krashto - did this help?  Did you try this out?

**Comment by pglombardo** [comment]
Hi @Krashto since I haven't head back I'm going to close this out.  I hope you worked out the issue.  That double underscore is required and is easy to miss.

If you have too many environment variables, you can always use a `settings.yml` file that you mount into the container.  Documentation on how to do that is available here:
https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#configuring-via-a-custom-settingsyml-file

If any issues remain, please let me know!
