### ISSUE TITLE
missing private.sqlite3 on pwpush-ephemeral container image

### ISSUE THREAD

**Issue by assices** [pglombardo/PasswordPusher#1058]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question
Hello,

refering to [448](https://github.com/pglombardo/PasswordPusher/discussions/448) I didn't find private.sqlite3 db in the container.
I deployed Password Pusher on Kubernetes and to gain data persistency I mounted /opt/PasswordPusher/db/db.sqlite3 file and it works.

Is this the expected behavior or am I missing something?

**Comment by pglombardo** [comment]
Hi @assices - the container image doesn't include that file - it's created on first boot.  When you mount that file externally, the application will [run the DB the migrations](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-ephemeral/entrypoint.sh#L6-L7) (table/column creations etc) on that file on boot.

So I would say that this is expected behaviour.

Does this help?

**Comment by pglombardo** [comment]
Ah you're right - the filename is `db.sqlite3` now.    It was changed recently in the [Dockerfile](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-ephemeral/Dockerfile#L18).

Your configuration is correct.  I'll update that discussion you linked.
