### ISSUE TITLE
Different URL for generated links

### ISSUE THREAD

**Issue by assices** [pglombardo/PasswordPusher#1101]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I would like restrict access to user console (anonymous and login mode) to a limited client IP ranges, but allowing generated links to any. 
I can do it with a reverse proxy in front to Password Pusher based on URL request, but I didn't find a way to uniquely identify generated links requests, by URL path pattern.
Is it possible?

If not, It could be very useful to have the possibility to configure a subpath prefix for generated links, or even better a dedicated hostname.

Something like:

**pwpush.example.com**              --> Password Pusher user console
**pwpush.example.com/share/generated_links**    --> generated links only

OR

**pwpush.example.com**     --> Password Pusher user console
**pwshare.example.com/generated_links**    --> generated links only

thanks

**Comment by pglombardo** [comment]
Hi @assices - Having all shared links under a common `share` path would be nice but we don't have that today.  But you should be still able to block on paths already.

Here is the overly detailed list with HTTP methods to allow anonymous access to.  It's slightly more complicated as well because of the locale support in URLs.

## Text based pushes

* GET `/p/:id`
* DELETE `/p/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/p/:id/r`
* GET `/p/:id/passphrase`
* POST `/p/:id/access`
* GET `/:locale/p/:id`
* DELETE `/:locale/p/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/:locale/p/:id/r`
* GET `/:locale/p/:id/passphrase`
* POST `/:locale/p/:id/access`

## URL based pushes

* GET `/r/:id`
* DELETE `/r/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/r/:id/r`
* GET `/r/:id/passphrase`
* POST `/r/:id/access`
* GET `/:locale/r/:id`
* DELETE `/:locale/r/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/:locale/r/:id/r`
* GET `/:locale/r/:id/passphrase`
* POST `/:locale/r/:id/access`

## File based pushes

* GET `/f/:id`
* DELETE `/f/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/f/:id/r`
* GET `/f/:id/passphrase`
* POST `/f/:id/access`
* GET `/:locale/f/:id`
* DELETE `/:locale/r/:id` (for "Allow users to delete this push once retrieved." option)
* GET `/:locale/f/:id/r`
* GET `/:locale/f/:id/passphrase`
* POST `/:locale/f/:id/access`

It depends on what features you have enabled on your instance but general path rules somewhat like the following would work:

```nginx
location /p/ {
    allow  all;
}
location /en/p/ {
    allow  all;
}
```

If you want a raw dump of all routes of the application, from inside the Docker container run `rails routes`.

<img width="1348" alt="Screenshot 2023-05-14 at 09 55 43" src="https://github.com/pglombardo/PasswordPusher/assets/395132/af8850b8-ce67-4462-a520-a59e1aca27a8">



Also note the other options available:`PWP__ALLOW_ANONYMOUS` and `PWP__DISABLE_SIGNUPS` in the [Configuration documentation](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#enabling-logins).

**Comment by assices** [comment]
Thanks Peter,

I think it's quite diffilcult to block shared links only by URL path without risking blocking other user management functions.

An example:

**Shared link (public access)**
https://pwpush.example.com/it/p/of7xq0slito7wgps8w

**user management links (restricted access)**
https://pwpush.example.com/it/p/of7xq0slito7wgps8w/anteprima
https://pwpush.example.com/it/p/of7xq0slito7wgps8w/controllo
https://pwpush.example.com/it/p/scaduto
https://pwpush.example.com/it/p/attivo

Anyway, I'll do some tests.

Yes, I evaluated `PWP__ALLOW_ANONYMOUS` and `PWP__DISABLE_SIGNUPS` options, but I would like leave both Anonynous and Signups enabled for company employees only.

Thanks again for informations.
Ciao, Andrea
