### ISSUE TITLE
Pre-shared Key Support - Add Retrieval Code/Password

### ISSUE THREAD

**Issue by devinmcelheran** [pglombardo/PasswordPusher#123]
Hi,

we use this product for relaying passwords over insecure means. But I think that to take it a step further in security, if there was an option to require a passcode to retrieve the password (hopefully communicated in a means other than the one used to communicate the URL) that would help. So, when creating the new pwpusher password, a checkbox to to create a passcode and then an input box to enter it. I think this would go a long way in securing the password from people attempting to snoop or intercept, adding another layer of protection.

Regards,
Devin

**Comment by pglombardo** [comment]
That's a fair request although I would think using a password to get a password would confuse a lot of non-technical users.

What's the core issue triggering the request?  Because the secret URL is communicated in a public place?  Then how would you communicate the access password?  Over the same insecure channel?

Trying to understand what the workflow would be...

**Comment by devinmcelheran** [comment]
My thought is that the URL can be communicated using one channel and the passcode over another, or the passcode would be a piece of information already known to the recipient but not to any potential eavesdroppers, like an employee ID or something else user-specific, like the asset tag of their company desktop/laptop or the serial of a mobile device (I'm just rambling random things, I hope it still demonstrates the idea).

**Comment by pglombardo** [comment]
Ok that makes sense and it would be a nice feature to add as an option on the front page (and via the REST API).

This is actually a fair amount of work so let's see if/when I can get some free time to implement this.

As I see it the tasks would be:

1. Passwords now have a form/app workflow since we can't securely validate this password in Javascript.
  e.g. If password has an access password, then show the challenge page first and conditionally the pushed password (max fail attempts?)
2. Update the database model to encrypt, store, use and expire the additional credential/access password
3. Expand the application model to support the access password handling
4. New application preliminary page/form to validate access password
5. Then add REST API support
6. Update front page to support this option

I'll leave this issue open for now to follow up on.

**Comment by nathanzych** [comment]
Hi,
Related to this request (somewhat) since you mention a workflow for this there is another application for that workflow...
If there could in addition to option for a password as suggested be an option to require the user to confirm retrieval of a password that would solve a big problem for us. We would want to enable this by default for all passwords since many UTM firewalls and email filters visit URLs found in emails automatically and that counts as a view. We find if setting to expire after 1 view many do not receive a usable URL as result unless we allow a higher number of views.
Thanks,
Nate

**Comment by JoinFreeMe** [comment]
> Hi,
> Related to this request (somewhat) since you mention a workflow for this there is another application for that workflow...
> If there could in addition to option for a password as suggested be an option to require the user to confirm retrieval of a password that would solve a big problem for us. We would want to enable this by default for all passwords since many UTM firewalls and email filters visit URLs found in emails automatically and that counts as a view. We find if setting to expire after 1 view many do not receive a usable URL as result unless we allow a higher number of views.
> Thanks,
> Nate

Adding to this, maybe not logging the page as accessed until the distorted field is clicked &/ the password is copied?

**Comment by pglombardo** [comment]
> Adding to this, maybe not logging the page as accessed until the distorted field is clicked &/ the password is copied?

Fair idea but that is just JS trickery so no real security.  Just obscuring the view for people looking over shoulders.  With this route a hand crafted greasemonkey script or chrome extension, you could make it so that passwords never eat up a view when you requested the page.

But along the same lines, if the secret URL had an access password, the view wouldn't get eaten up until the right access password was entered.

These are all great suggestions - much appreciated.

**Comment by pglombardo** [comment]
Update to this issue which hasn't been updated in a while.

Password Pusher now has a Push Lockdown feature - essentially pre-shared key support as @devinmcelheran requested.  🥳 

<img width="805" alt="Screenshot 2023-09-01 at 16 29 54" src="https://github.com/pglombardo/PasswordPusher/assets/395132/f14800ff-7334-4669-8b1f-a29038a4086f">

And as for the requests by @JoinFreeMe & @nathanzych although we don't have a enforced way for users to confirm receipt, we do now have Audit logs and the user can optionally delete the push upon receipt.

<img width="1309" alt="Screenshot 2022-12-28 at 11 15 49" src="https://github.com/pglombardo/PasswordPusher/assets/395132/d21dba57-36a9-4fc2-9062-bb4832e39bd4">

<img width="446" alt="Screenshot 2023-09-01 at 16 32 55" src="https://github.com/pglombardo/PasswordPusher/assets/395132/1386f4b0-3a67-42b1-925f-7384ca7701b9">

Apologies for the late update.  I hope all is well with everyone.

Given that the original request has been implemented I'll close out this issue.

If anything remains, please let me know or feel free to open another.
