### ISSUE TITLE
Add a more modern design/theme

### ISSUE THREAD

**Issue by CWempe** [pglombardo/PasswordPusher#179]
I just found this project and thik the idea is relly great.

But my first thought was: "This looks like an old website".
Don't get me wrong. I am no UX designer myself. 😄 

There are like eight different font styles used.
And all (expect the password) use a font with serifs.

I like the design from @PUPeter:
https://github.com/pglombardo/PasswordPusher/issues/164#issuecomment-778862382
Fun fact: He only uses a serif font for the password. 😄 
But I think this makes sense and looks much more modern.

And dynamic dark/light themes would be great, too.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

In the mean time I can try to sutomize `/app/assets/stylesheets/passwords.css.scss` myself, I guess. 😉

**Comment by pglombardo** [comment]
It's a fair point and I don't disagree.   The CSS is the victim of random updates since 2012.    I like the idea of the dynamic dark/light themes for sure.

I was just cleaning up some of the CSS today and have the latest changes on master.  It still needs more work and simplification as you pointed out.  You can see the latest changes on [this staging app](https://pwp-stage.herokuapp.com) that I plan on pushing to pwpush.com this weekend.

A PR would be a big help as long as the spirit of the theme is maintained.  I'm a bit attached to the simplicity of the black/yellow but a light theme would be a great addition.  Unifying on one font and cleaning up the old CSS elements would be a big improvement.

The one part to make note of is that I've had issues filed in the past regarding the font of the password where it didn't show the difference between O0Il (zeros, Os, i's and L's) well. 

If you don't get a chance, I'll get to this eventually.  Thanks for pointing this out.  Any other ideas/issues/PRs are always welcome.

**Comment by CWempe** [comment]
> The one part to make note of is that I've had issues filed in the past regarding the font of the password where it didn't show the difference between O0Il (zeros, Os, i's and L's) well.

I am sure there are people that can recommend a good font for this.
Usually fonts that are used for coding are good at this, I think.

Like:
https://www.jetbrains.com/lp/mono/#:~:text=Distinctiveness%20of%20symbols
https://dejavu-fonts.github.io/

> If you don't get a chance, I'll get to this eventually.

I do not think I will have time for this.
And I feel other people are much better at creating a good design. 😄

**Comment by pglombardo** [comment]
How is this?
https://github.com/pglombardo/PasswordPusher/pull/199

If you can, put in your vote here:
https://twitter.com/pwpush/status/1403727193776209925

**Comment by pglombardo** [comment]
After a summer vacation delay, an updated theme is going out this weekend.  Thanks for your input!

**Comment by pglombardo** [comment]
Hi @CWempe - you might be interested in these [custom theme instructions](https://github.com/pglombardo/PasswordPusher/issues/762#issuecomment-1416718368).

It's a short term work around for eventual selectable themes.
