### ISSUE TITLE
Whitespace stripping in passwords

### ISSUE THREAD

**Issue by rev138** [pglombardo/PasswordPusher#196]
Our PasswordPusher instance seems to be stripping/condensing multiple whitespace characters in passwords.

For example, this text entered into the form:

<pre>there are two spaces before the period  .</pre>

Becomes the following text displayed by the resulting link:

<pre>there are two spaces before the period .</pre>

Obviously, this is bad behavior for password handling. It led to a several hours of tail-chasing at my workplace this morning :(

Thank you for your efforts.

**Comment by pglombardo** [comment]
Thanks for letting me know @rev138.  I just tried to reproduce on the latest and even prior deploys from last month and it happens on both.  I'll figure out the root cause and update soon.

**Comment by pglombardo** [comment]
The good news is that this was a display issue only because of a CSS oddity with `white-space` collapsing.

![Screen Shot 2021-06-08 at 7 54 08 PM](https://user-images.githubusercontent.com/395132/121235132-cfaf0180-c894-11eb-8396-99631230fd13.png)

I have a fix on the staging site and will deploy to pwpush.com shortly.  Give it a try and let me know:
https://pwp-stage.herokuapp.com/p/lxs8nylvzgousi81

Apologies for the time burnt with this issue - it was an unexpected one for sure.

**Comment by pglombardo** [comment]
The fix is released on pwpush.com.  That should cover everything.  If anything remains, feel free to open another issue.  Thanks for reporting.
