### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by ataylor1988** [pglombardo/PasswordPusher#248]
Is there an easy way to change the Logo on self hosted docker instances?
It would be nice to be able to do some custom branding on this, of course if that is ok with the creator.

**Comment by pglombardo** [comment]
I have no problem with re-branding at all.  Some have done this by forking the repo and modifying the CSS.

I've started some work in this direction to offer containers stripped of branding (including the footer) and a custom title & logo but I haven't finished this yet.    Once I get this implemented, I'll update this issue.

**Comment by JordMonte512** [comment]
Hi, 

Has there been any news on this?
I love PW Pusher and I am about to attempt the CSS modification in a forked repo however if this is coming soon I will hold off and wait for the official implementation?

Thanks in advance!

**Comment by pglombardo** [comment]
Hi @JordMonte512 - I actually started working on customization this week.  Give me a bit of time, and I should have something out soon.

![Screen Shot 2022-08-07 at 11 49 31](https://user-images.githubusercontent.com/395132/183285253-583b2015-b75c-4a1f-af7f-6dc34d90f0ab.png)

The idea so far is that there is one central config file that can be replaced in the container with all the customizations: `config/settings.yml`

**Comment by JordMonte512** [comment]
Awesome, that's amazing. Thank you for the update!

**Comment by pglombardo** [comment]
The code for this has been merged, documentation [here](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#rebranding) and I will have new Docker containers tagged before the end of the weekend.

Thanks all for reporting/requesting this.

**Comment by RainerZufahl** [comment]
Hey, I'm trying to get on this branding train as well, but am not totally sure how it works yet. 
I've installed pwpush via the mysql docker container (not entirely sure which version number, since i'm simply running latest), mounted a host path inside the container, provided media assets and passed on the environment variables to change name, tagline and the logos. I've also confirmed from inside the pwpush container that the environment variables have been received properly by the container, yet nothing on the website changed.

Are there any additional flags one would need to switch for branding overrides to kick in? Or has this feature not yet been entirely implemented?

**Comment by pglombardo** [comment]
Ok that's a good point.  I need to test this too as the app has a media/asset packer which fingerprints most IDs but if it's working for you that's great.

I assumed most will use external addresses with fully qualified URLs such as `https://disznc.s3.amazonaws.com/Screen-Shot-2022-08-11-at-10.40.35.png`

**Comment by pglombardo** [comment]
For others coming to this issue, the documentation on branding is here: https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#rebranding
