### ISSUE TITLE
Feature request: Language-agnostic link by default

### ISSUE THREAD

**Issue by n-engelhardt** [pglombardo/PasswordPusher#249]
After creating a push, it brings you to a page with the secret link. By default, this links to the password on a language-specific page, with the language being the language you're viewing it in. There's a dropdown on the right to change the language of the link. However, if you take that link and just remove the language portion of the URL, it makes the link language-agnostic. So changing it from https://pwpush.com/[language code]/p/[push ID]/r to https://pwpush.com/p/[push ID]/r

This link should be the default, allowing you to change it to a language-specific link if desired.

**Comment by pglombardo** [comment]
Hi @n-engelhardt - very late update but Password Pusher now uses the "Accept-Language" header like you suggested.  Also all the language locale paths are gone (e.g. `/en`, `/de`, `/es` etc..).  It's much simpler and smarter this way.

I've made a million changes since 2021.  Take a look and if you have any question/issues let me know.  I'd be happy to help out.

**Comment by Yudis53732** [comment]
Pada Min, 1 Sep 2024 23.08, Peter Giacomo Lombardo ***@***.***>
menulis:
