### ISSUE TITLE
Idea: Alfred workflow

### ISSUE THREAD

**Issue by psteinweber** [pglombardo/PasswordPusher#29]
Hi,

I'm a happy and frequent user of the hosted version of this tool.

I have an idea, and I hope it's ok to simply write it here. It would be great to have the opportunity to create pwpush URLs with [Afred](http://www.alfredapp.com/). I imagine it like:

Launch alfred > type in "pwp mypassword" > A pwpush.com site for this password opens (some default settings), and it's URL is copied into the clipboard automatically

Possible at all? Just dreaming :)

Philipp

**Comment by pglombardo** [comment]
Hey @psteinweber !  That's a great idea.

I've had an item on the list for a long time to create a command line utility but since that hasn't happened how's this?  https://dl.dropboxusercontent.com/u/20854929/PasswordPusher.alfredworkflow

It requires bash, curl, sed and awk but if you have those installed, this should work.  Let me know.

**Comment by psteinweber** [comment]
That sounds and looks amazing. Will give it a try ASAP!

**Comment by psteinweber** [comment]
Works great! Thanks for implementing it, and even that quickly. Total game changer for me personally.

**Comment by pglombardo** [comment]
@psteinweber I built a slighter better interface that uses only Ruby and posted it on packal: http://www.packal.org/workflow/passwordpusher

Best!
Peter
