### ISSUE TITLE
Git clone not working

### ISSUE THREAD

**Issue by rshosting** [pglombardo/PasswordPusher#426]
Hello,

I am trying to follow the guide to install Password Pusher via git and I get below error :

> git clone git@github.com:pglombardo/PasswordPusher.git
> Cloning into 'PasswordPusher'...
> Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Can someone help me fix above error please?

**Comment by pglombardo** [comment]
That's likely because your SSH key isn't added to your Github account.  Try the HTTPS clone url instead:

`git clone https://github.com/pglombardo/PasswordPusher.git`

![Screenshot 2022-10-11 at 15 26 13](https://user-images.githubusercontent.com/395132/195103756-1143555c-46ca-458c-bab2-dc8063ceadfb.png)

Some resources:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh
https://stackoverflow.com/questions/55449921/permission-denied-publickey-error-when-trying-to-clone-from-github

Let me know if this helps.

**Comment by pglombardo** [comment]
Hi @rshosting - did you get the clone command working?

**Comment by rshosting** [comment]
@pglombardo Yes got it working :) Sorry for delayed reply.. Thank you so much @pglombardo

**Comment by pglombardo** [comment]
Happy to hear!  Let me know if any other issues come up.
