### ISSUE TITLE
Rails 3.2 is EOL

### ISSUE THREAD

**Issue by CodeGnome** [pglombardo/PasswordPusher#56]
Rails 3.2 is end-of-life. A security-oriented tool like PasswordPusher should not be running on a platform that will not receive timely security patches or bug fixes. The code base should be upgraded to Rails 5.x to ensure it receives essential security updates for the underlying platform.

http://guides.rubyonrails.org/maintenance_policy.html#unsupported-release-series

**Comment by pglombardo** [comment]
Unfortunately this has been on the list for quite some time.  And since then, I've considered re-implementing PasswordPusher in a lighter framework since it's a very targeted app.  Rails is somewhat overkill.

Sinatra, Padrino, Roda or Cuba are nice alternatives although no decisions so far.  Those would likely reduce the barrier to entry for PasswordPusher too.

Time is the issue but not all hope is lost.  One weekend soon I may get to this 😸 

Thanks for the note!

**Comment by CodeGnome** [comment]
Sinatra has my vote, if you switch. The main issue is that Sinatra (and others) will require you to add in your own ORM, and won't necessarily have a testing framework built in. I'm not sure that Rails is the source of any actual pain points for the app. Any perceived benefit of switching is probably a premature optimization in this specific use case.

**Comment by pglombardo** [comment]
The app has been updated to Rails 4.2 for now.  Rails 5 on the list once Rails 4.2 shows stable/no issues.  A complete framework change (e.g. Sinatra) is still an option but this is the easy step for the time being considering my schedule.

Any other questions/concerns, don't hesitate.
