### ISSUE TITLE
Implement passphrase option to further secure

### ISSUE THREAD

**Issue by jonnjonzzn** [pglombardo/PasswordPusher#836]
## 🚀 Feature Request

Add a passphrase entry field to "Passwords/Files/URLs" to further secure information. Someone would also need the passphrase in addition to the URL.  This would be optional.

## 🔈 Motivation

We currently use  https://onetimesecret.com/ which has this feature. See "Privacy Options" in that link. Also see below. Motivation: Makes my job convincing IT Security to make the switch to PW Pusher easier ;-)

## 🛰 Alternatives

Stay as is and do not implement.

## 📎 Additional context

![Screenshot from 2023-02-16 08 52 15](https://user-images.githubusercontent.com/5324000/219398693-e5701e2b-6b7c-4e63-abaf-4333a44a9356.png)

**Comment by pglombardo** [comment]
Hi @jonnjonzzn - this is definitely on the radar.  Not sure when exactly yet (hopefully soon) but once I have an update, I'll make sure to post back here.  Thanks for pointing this out!

**Comment by Viajaz** [comment]
Despite Microsoft's [own advice](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#some-common-approaches-and-their-negative-impacts), many of us are still bound by Microsoft's own [password complexity requirements](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements#reference) in the real-world. Some application have also followed suit in modeling their own requirements off of Microsoft's in varying ways.

We use the PwPush API with our own front-end and our passphrase generator variant will use capitalise, where appropriate, and punctuate the phrase in order to meet these requirements, such as:
`Impress Deeply Soil?`
`Order Society Competitive!`

It would be useful to have a checkbox to enable this.

**Comment by jonnjonzzn** [comment]
@Viajaz is this comment better placed attached to this Issue? https://github.com/pglombardo/PasswordPusher/discussions/472

**Comment by jonnjonzzn** [comment]
Any updates on this feature request?  Anything I could to do help?  Thank you!

**Comment by pglombardo** [comment]
Unfortunately nothing tangible yet @jonnjonzzn - but I'm trying.  Working on requested Oauth2 support and then will likely take this up next.  Apologies - day job and limited OSS time but I'll get there.

**Comment by pglombardo** [comment]
A bit of progress:

<img width="967" alt="Screenshot 2023-04-06 at 18 45 58" src="https://user-images.githubusercontent.com/395132/230444107-f23b1f8b-65d7-4a16-879e-0e7f768094b4.png">
<img width="1324" alt="Screenshot 2023-04-06 at 18 46 21" src="https://user-images.githubusercontent.com/395132/230444118-8245210e-e472-4ef0-b5e0-0a540ede76e5.png">
<img width="1302" alt="Screenshot 2023-04-06 at 18 46 09" src="https://user-images.githubusercontent.com/395132/230444124-eecc09d4-8489-41bb-b203-09ae393712b6.png">

**Comment by pglombardo** [comment]
Passphrases are live in [release v1.28.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.0).  They are supported for all text, file and URL pushes.

Although I tested it quite thoroughly, give it a spin and let me know if you see any issues.

https://pwpush.com

I'll close this issue since this feature is out but I'll re-open if any issues are identified.

Thanks for filing/pointing out this feature!
